services:
  web:
    image: odoo:17.0
    container_name: odoo17_web
    depends_on:
      - db
      - nginx
    ports:
      - "5001:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
      - ./data/odoo-web-data:/var/lib/odoo
      - ./logs:/var/log/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: odoo17_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - ./data/odoo-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: odoo17_nginx
    # depends_on:
    #   - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/letsencrypt
      - ./logs/nginx:/var/log/nginx
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: odoo_certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    entrypoint: >
      /bin/sh -c "trap exit TERM;
      while :; do
        certbot renew;
        sleep 12h & wait $${!};
      done"
    restart: unless-stopped

volumes:
  odoo-web-data:
  odoo-db-data:
