from . import patient
from . import provider
from . import consultation
from . import diagnosis
from . import testing
from . import prescription
from . import fulfillment
from . import vaccination
from . import product
from . import res_users
